version: '3'
services:
  web:
    build: .
    ports:
      - "3090:3000"
      # - "9229:9229"
    command: ./node_modules/.bin/nodemon
    volumes:
      - .:/data
    working_dir: /data
    environment:
      - NODE_ENV=development
